### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by shrektan** [shrektan/shrektan_blog#1]
### 2018/04

- [x] [The timezone issue of the filter in DT](https://github.com/rstudio/DT/issues/241)
    - the best approach is to pass the formatter via `formatDate()`, that is to check if the `filter` is `TRUE` and pass the info to javascript via `x$option`
    - [the place to change](https://github.com/rstudio/DT/blob/8ba54abd4e4b1215908aae83981f4b51d3be1984/inst/htmlwidgets/datatables.js#L535)
    - DONE via https://github.com/rstudio/DT/pull/522
- [ ] The review for [the editing improvement of DT](https://github.com/rstudio/DT/pull/509)
    - I think let's make it simpler just improve the PR and submit because it's quite difficult to get the feels that right... Time costly and I just don't have that time 😢 
    - Focus on : 
         1. allows only parts of the columns to be edited
         1. allows some columns to have the dropdown input at editing
         1. deleting some rows??
- [ ] a blog about how to build a shiny app using [shinyserver](https://www.rstudio.com/products/shiny/shiny-server/) & [docker](https://www.docker.com/) in [digitocean](https://www.digitalocean.com/) or [aliyun](https://www.aliyun.com/), since I've just updated the [maptcm](http://www.maptcm.net) again, fresh memory... address on: 
    - add some customized javascript
    - how to boost the app's opening speed in China, like you may want to use a domestic CDN because normally your app will retrieve resources from overseas...
    - tips for tweaking the UI
    - the shinyserver deployed using docker - how to create your own and deploy, how to speed up like hub.docker.com is far too slow in aliyun, or you want to deploy docker in your office but can't retrieve image from the hub...
    - further ways of improving like using `https`
    - should you use [shiny-proxy](https://www.shinyproxy.io/) or [shinyserver](https://www.rstudio.com/products/shiny/shiny-server/)
    - ahhhh, too much....
- [x] enable the test in the `data.table` encoding PR being run on a Linux or English Windows machine
- [x] `data.table`'s test should be changed to the `latin1` encoding instead of GB2312 because the former is available to be tested on any platform.
- [ ] Add a visitor counter at the homepage of maptcm
